# Generated by Django 4.2.1 on 2023-06-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.TextField(max_length=10, verbose_name='Placa')),
                ('color', models.CharField(max_length=15, verbose_name='Color')),
                ('marca', models.CharField(max_length=15, verbose_name='Marca')),
                ('tipo', models.CharField(max_length=10, verbose_name='Tipo de Vehiculo')),
                ('parqueadero', models.CharField(max_length=5, verbose_name='Parqueadero Asignado')),
                ('propietario', models.CharField(max_length=50, verbose_name='Nombre del propietario')),
                ('cedula', models.CharField(max_length=12, verbose_name='Identificaion del propietario')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono del propietario')),
                ('apartamento', models.CharField(max_length=7, verbose_name='Apartamento')),
                ('tipoPropietario', models.CharField(max_length=10, verbose_name='¿Visitante o residente?')),
            ],
        ),
    ]
